---
# tasks file for sshpass

- name: Include distribution specific variables
  include_vars: "{{ ansible_distribution }}.yml"
  tags: sshpass

- include: CentOS.yml
  when: ansible_distribution == "CentOS"
  tags: sshpass

- include: Ubuntu.yml
  when: ansible_distribution == "Ubuntu"
  tags: sshpass
